name: BIT Auto Leave
on:
  workflow_dispatch:
  schedule:
    - cron: '03 15 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天UTC时间的22点05分整， 北京时间的06点05分（24小时制）
    # 可在此网站查询UTC时间和北京时间的换算关系 https://datetime360.com/cn/utc-beijing-time/

jobs:
  Leave:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
    - name: Run
      env:
        TZ: Asia/Shanghai
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TELEPHONE: ${{ secrets.TELEPHONE }}
      run: |
        sudo apt-get install python3-setuptools -y
        git clone https://github.com/YoungKlaus/BIT_Auto_Leave.git
        cp -r BIT_Auto_Leave/* .
        pip3 install -r requirements.txt
        python3 BIT_leave.py
        
